Develop
pastorp3/Advanced-Building-Blocks---Bubble-Sort pull request #1
Opened 2020-08-12 16:09 UTC by pastorp3

2020-08-12 16:49 UTC, atenaiis commented
We have worked this project collaborative as requested, targeting the aim to do a bobble sort without using the sorting but the loop and the yield.

kindle ask if you could help us fixing the error on rubocop, we have tried but did not manage to do it.

Cheers.

2020-08-13 01:44 UTC, kitpao requested changes
# 👋 Hello @pastorp3 and @atenaiis 

Great job implementing the sorting methods 👏 your logic is nice and clean and you tried different ways of implementing the loops and checks 🌟

✏️ The requested changes are outside of the core ruby code, but they are still important to have a professional repo. Please check them below 🔽 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [x] For next time, remember to write your commits in the imperative tense, as stated in [the article pointed in pathwright](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

- [x] Please use a more meaningful title for your pull request
![image](https://user-images.githubusercontent.com/53256139/90084590-56c63400-dcdb-11ea-9500-db749173735a.png)

- [x] Notice that your .rubocop.yml file is in the wrong directory, it should be in the root path as stated in [Microverse instructions](https://github.com/microverseinc/linters-config/tree/master/ruby). Please move it.
![image](https://user-images.githubusercontent.com/53256139/90082054-7017b200-dcd4-11ea-9ea2-36aa5294724a.png)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-13 01:44 UTC, kitpao commented on README.md
> +- Download Ruby from https://www.ruby-lang.org/en/ to run it locally .
- [x] You have a typo here (Install), please correct it so that it looks professional

2020-08-13 01:44 UTC, kitpao commented on README.md
> +> This is a collaborative project with Ruby for a Buble_sort.
- [x] Please fix your typo to make your readme professional (Bubble)

2020-08-13 01:44 UTC, kitpao commented on main.rb
> +def buble_sort_by(array)
- [ ] **OPTIONAL** You can name your methods as you like as long as they are descriptive, but as a recommendation, try to avoid typos (bubble). [Also in line 29]

2020-08-13 01:44 UTC, kitpao commented on README.md
> +-Run code with ruby main.rb in your local terminal
- [ ] **OPTIONAL** You can add inline `code snippets` <-- by surrounding the code with backquotes (`)

2020-08-13 14:48 UTC, atenaiis commented
Thank you for the review,
we have worked on the changes requested.

cheers.

2020-08-13 23:31 UTC, krys2fa approved these changes
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-08-13 23:34 UTC, merged